#!/bin/sh

# Mouse config
xinput --set-prop "Logitech Gaming Mouse G502" "libinput Accel Profile Enabled" 0, 1
xinput --set-prop "Logitech Gaming Mouse G502" "libinput Accel Speed" -0.15

# Cursor stays cursor on wallpaper
xsetroot -cursor_name left_ptr

# Set the wallpaper
xwallpaper --zoom ~/.config/wall.jpg

# Start startup programs
sxhkd &
picom &
unclutter &
$XDG_CONFIG_HOME/polybar/launch.sh &
#nm-applet &
#blueman-applet &
udiskie &

# Start mpd if not already running
pgrep -x mpd > /dev/null || mpd && mpc stop

# Configure bspwm
bspc monitor primary -d 1 2 3
bspc monitor primary#west -d 4 5 6

bspc config border_width          2
bspc config window_gap            12

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focus_follows_pointer true

bspc config normal_border_color   "#282828"
bspc config focused_border_color  "#d5c4a1"
bspc config active_border_color   "#282828"

bspc config single_monocle        true

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

bspc rule -a Thunderbird desktop=5
bspc rule -a whatsapp-nativefier-d40211 desktop=5
